#!/bin/bash
clear
echo "______________       _____       "
echo "___  __ \__  /_________  /______ "
echo "__  /_/ /_  __ \  __ \  __/  __ \\"
echo "_  ____/_  / / / /_/ / /_ / /_/ /"
echo "/_/     /_/ /_/\\____/\\__/ \\____/ "
printf "Write \"aap\" File\'s Path And Enter To Start\n"
read dir
clear
for c in `cat $dir | fold -1`
do
    case $c in
        "r" ) printf "\33[0;39m\n" ;;
        * ) printf "\033[0;$(( $c + 40));30m   " ;;
    esac
done
read -p "OK?"
exit

#黒→0→40
#赤→1→41
#緑→2→42
#黄→3→43
#青→4→44
#マゼンタ→5→45
#シアン→6→46
#白→7→47
#行終わり→r
#clear