#!/bin/bash

test "$1" = "-h"
if [ $? -eq 0 ]; then
    printf "$0 [-h] <回数> <間隔(秒)>\n  h : この文章を表示する\n"
    exit
fi
for A in `seq $1`; do
    terminal-notifier -title "姿勢.sh" -subtitle "姿勢に気をつけよう" -message "頑張れ" -sound default
    sleep $(($2))
done
exit
