# [[plugins]]
# repo = 'sainnhe/everforest'
# hook_add = '''
# set background=dark
# autocmd VimEnter * nested colorscheme everforest
# '''

# [[plugins]]
# repo = 'rakr/vim-one'
# hook_add = '''
# set background=dark
# autocmd VimEnter * nested colorscheme one
# '''

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_add = '''
colorscheme nightfly
let g:lightline['colorscheme'] = 'nightfly'
'''
