[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = ['InsertEnter']
depends = ['denops.vim']
hook_source = '''
call ddc#custom#patch_global({
      \ 'backspaceCompletion': v:true
      \ })

" ソース・マッチャー・ソーターを追加
call ddc#custom#patch_global('sources', [
      \ 'around',
      \ 'vim-lsp',
      \ 'file',
      \ ])
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank']
      \ },
      \ 'vim-lsp': {
      \   'matchers': ['matcher_head'],
      \   'mark': ' ',
      \ },
      \ })

" ソースの目印
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'minAutoCompleteLength': 1,
      \ },
      \ 'around': {'mark': ' '},
      \ })

call ddc#custom#patch_global('sourceOptions', {
      \ 'file': {
      \   'mark': ' ',
      \   'isVolatile': v:true,
      \   'minAutoCompleteLength': 1000,
      \   'forceCompletionPattern': '\S/\S*'
      \ },
      \})

" <Tab>で順繰り
inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

" 有効化
call ddc#enable()
'''

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'
