[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/remote'
hook_add = '''
nnoremap <silent> <c-f>p     :<C-u>FzfPreviewFromResources project_mru git<CR>
nnoremap <silent> <c-f>gs    :<C-u>FzfPreviewGitStatus<CR>
nnoremap <silent> <c-f>ga    :<C-u>FzfPreviewGitActions<CR>
nnoremap <silent> <c-f>b     :<C-u>FzfPreviewBuffers<CR>
nnoremap <silent> <c-f>B     :<C-u>FzfPreviewAllBuffers<CR>
nnoremap <silent> <c-f>o     :<C-u>FzfPreviewFromResources buffer project_mru<CR>
nnoremap <silent> <c-f><C-o> :<C-u>FzfPreviewJumps<CR>
nnoremap <silent> <c-f>g;    :<C-u>FzfPreviewChanges<CR>
nnoremap <silent> <c-f>/     :<C-u>FzfPreviewLines --add-fzf-arg=--no-sort --add-fzf-arg=--query="'"<CR>
nnoremap <silent> <c-f>*     :<C-u>FzfPreviewLines --add-fzf-arg=--no-sort --add-fzf-arg=--query="'<C-r>=expand('<cword>')<CR>"<CR>
nnoremap          <c-f>gr    :<C-u>FzfPreviewProjectGrep<Space>
xnoremap          <c-f>gr    "sy:FzfPreviewProjectGrep<Space>-F<Space>"<C-r>=substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g')<CR>"
nnoremap <silent> <c-f>t     :<C-u>FzfPreviewBufferTags<CR>
nnoremap <silent> <c-f>q     :<C-u>FzfPreviewQuickFix<CR>
nnoremap <silent> <c-f>l     :<C-u>FzfPreviewLocationList<CR>
nnoremap <silent> <c-f>m     :<C-u>FzfPreviewMrwFiles<CR>
'''
