# ==============================================================================
# Others
[[plugins]]
repo = 'kat0h/radiru.vim'
on_cmd = ['RadiruPlay', 'RadiruPlayStop']

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = 'cabbrev git Gina'
on_cmd = 'Gina'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]]
repo = 'mhinz/vim-sayonara'
on_cmd = 'Sayonara'

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = ['f', 'F', 't', 'T']
hook_add = '''
map ; <Plug>(clever-f-repeat-forward)
map , <Plug>(clever-f-repeat-back)
'''

[[plugins]]
repo = 'skanehira/translate.vim'
on_cmd = 'Translate'
hook_add = '''
nnoremap <leader>t :Translate<CR>
vnoremap <leader>t :Translate<CR>
'''


# ==============================================================================
# Fern.vim

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = ['Fern', 'FernDo']
depends =  ['fern-git-status.vim', 'fern-preview.vim', 'fern-renderer-nerdfont.vim']
hook_source = '''
let g:fern#disable_viewer_spinner = 1
augroup VimrcFern
  autocmd!
  " autocmd FileType fern setlocal nocursorline
  autocmd FileType fern setlocal nonumber
  autocmd FileType fern call s:fern_settings()
augroup END
function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent><expr> <buffer> <C-d> fern_preview#is_win_visible()?"<Plug>(fern-action-preview:scroll:down:half)":"<C-d>"
  nmap <silent><expr> <buffer> <C-u> fern_preview#is_win_visible()?"<Plug>(fern-action-preview:scroll:up:half)":"<C-u>"
endfunction
'''
hook_add = '''
nnoremap <leader>f :Fern . -drawer -toggle<CR>
'''

[[plugins]]
repo = 'kat0h/fern-preview.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = 'fern.vim'
depends = ['nerdfont.vim', 'glyph-palette.vim']
hook_source = '''
let g:fern#renderer = "nerdfont"
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
augroup END
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

# ==============================================================================
# denops.vim
[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
'''

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
hook_source = '''
if !filereadable(expand('~/.config/skk/SKK-JISYO.L'))
  call mkdir(expand('~/.config/skk'), 'p')
  call system('cd ~/.config/skk && wget http://openlab.jp/skk/dic/SKK-JISYO.L.gz && gzip -d SKK-JISYO.L.gz')
endif

imap <C-j> <Plug>(skkeleton-toggle)
cmap <C-j> <Plug>(skkeleton-toggle)

function! s:skkeleton_init() abort
  call skkeleton#config({
        \ "globalJisyo": expand("~/.config/skk/SKK-JISYO.L"),
        \ "markerHenkan": "✋",
        \ "markerHenkanSelect": "✊"
        \})
endfunction
autocmd User skkeleton-initialize-pre call s:skkeleton_init()
'''

[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'
depends = 'denops.vim'
on_cmd = 'GhostStart'

[[plugins]]
repo = '~/dev/kato-k/dps-mdpreview'
depends = 'denops.vim'
on_cmd = ['PreviewMarkdown', 'PreviewMarkdownClose', 'PreviewMarkdownToggle']
hook_add = '''
'''
