# カラースキーム
[[plugins]]
repo = 'sainnhe/forest-night'
hook_add='''
let g:forest_night_disable_italic_comment = 1
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
hook_add = '''
let g:tokyonight_enable_italic = 0
'''

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'arzg/vim-colors-xcode'

[[plugins]]
repo = 'kjssad/quantum.vim'

[[plugins]]
repo = 'pineapplegiant/spaceduck'

[[plugins]]
repo = 'ulwlu/elly.vim'

# カラースキーム用のヘルパープラグイン
[[plugins]]
repo = 'kato-k/vim-colorscheme-settings'
hook_add = '''
let g:colorschemes_settings#use_default_colorschemes = v:false
colorscheme everforest
set bg=dark
'''
