[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
nnoremap <leader>f <cmd>Fern . -drawer -toggle<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
let g:fern#renderer = "nerdfont"
'''
