# LintTool
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
"ALEの設定
let g:airline#extensions#ale#enabled = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error   = ' '
let g:ale_sign_warning = ' '
"タイムアウト時間の調整
"let g:ale_lint_delay = 1000
" 言語に適したlintツール
let g:ale_linters = {
\   'python': ['flake8'],
\}
'''

# 括弧の対応の可視化
[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
"カッコのハイライト標準オフ
let g:loaded_matchparen = 1
""カッコの対応
source $VIMRUNTIME/macros/matchit.vim
'''

# fzfのvimフロントエンド
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
" fzfは単体でインストールしているのでそこへのパス
set rtp+=/usr/local/opt/fzf
" dotファイルを含める&プレビュー
command! -bang -nargs=? -complete=dir Files
\ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'source': 'ag --hidden --ignore .git -g ""'}), <bang>0)
command! -bang -nargs=* Ag
\ call fzf#vim#grep(
        \   'ag --column --color --hidden --ignore .git '.shellescape(<q-args>), 0,
        \   <bang>0 ? fzf#vim#with_preview('up:60%')
        \           : fzf#vim#with_preview('right:50%', '?'),
        \   <bang>0)
" キーバインド
nnoremap \b :Buffers
nnoremap \f :Files 
nnoremap \t :Tags
'''

# 行頭行末にあるスペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# インデントの可視化
# [[plugins]]
# repo = 'Yggdroot/indentLine'
# hook_add = '''
# let g:indent_guides_guide_size = 1
# '''

# ファイルの差分を表示
# :GitGutterToggle
# :GitGutterLineHighlightsToggle
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_sign_added = ' '
let g:gitgutter_sign_modified = ' '
let g:gitgutter_sign_removed = ' '
let g:gitgutter_sign_removed_first_line = ' '
let g:gitgutter_sign_modified_removed = ' '
'''
 [[plugins]]
 repo = 'tpope/vim-rhubarb'

# gcでコメントの切り替えができる
[[plugins]]
repo = 'tpope/vim-commentary'

# textobjの拡張基礎
[[plugins]]
repo = 'kana/vim-textobj-user'

# ステータスラインの拡張
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
set laststatus=2
set noshowmode
let g:airline_theme = 'bubblegum'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#wordcount#enabled = 0
let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
let g:airline_section_c = '%t'
let g:airline_section_x = '%{&filetype}'
let g:airline_section_z = '%{airline#extensions#ale#get_warning()} %{airline#extensions#ale#get_error()}'
let g:airline#extensions#ale#error_symbol = ' '
let g:airline#extensions#ale#warning_symbol = ' '
let g:airline#extensions#default#section_truncate_width = {}
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
set t_Co=256
let g:airline_powerline_fonts = 0
'''

# airline用カラースキーム
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# 様々なアイコンを追加
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# S で括弧の追加等ができる
[[plugins]]
repo = 'tpope/vim-surround'

# 括弧の補完
[[plugins]]
repo = 'Raimondi/delimitMate'

# Git操作ができる
# 専らAirLine用
 [[plugins]]
 repo = 'tpope/vim-fugitive'

# 最近使ったファイル
# [[plugins]]
# repo = 'mhinz/vim-startify'
# hook_add = '''
# " startify
# let g:startify_files_number = 10
# let g:startify_list_order = [
        # \ ['♻  最近使ったファイル:'],
        # \ 'files',
        # \ ['♲  最近使ったファイル(カレントディレクトリ下):'],
        # \ 'dir',
        # \ ['⚑  セッション:'],
        # \ 'sessions',
        # \ ['☺  ブックマーク:'],
        # \ 'bookmarks',
        # \ ]
# let g:startify_bookmarks = []
# '''

# . の強化
[[plugins]]
repo = 'tpope/vim-repeat'

# endの挿入
[[plugins]]
repo = 'tpope/vim-endwise'

# colorscheme
# [[plugins]]
# repo = 'itchyny/landscape.vim'
# hook_add = '''
# " colorscheme landscape
# '''

# [[plugins]]
# repo = 'scrooloose/nerdtree'
# hook_add = '''
# nnoremap <silent><C-e> :NERDTreeToggle<CR>
# '''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]]
repo = 'keith/swift.vim'

[[plugins]]
repo = 'skanehira/translate.vim'

# BDでいい感じにバッファをkillできる
[[plugins]]
repo = 'qpkorr/vim-bufkill'

[[plugins]]
repo = 'skanehira/train.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'https://github.com/itchyny/dictionary.vim'
