-- require("emcl").setup {}

-- dial.nvim
-- vim.cmd [[
--   nmap  <C-a>  <Plug>(dial-increment)
--   nmap  <C-x>  <Plug>(dial-decrement)
--   vmap  <C-a>  <Plug>(dial-increment)
--   vmap  <C-x>  <Plug>(dial-decrement)
--   vmap g<C-a> g<Plug>(dial-increment)
--   vmap g<C-x> g<Plug>(dial-decrement)
-- ]]

-- require('Comment').setup {}
-- 
-- 
-- vim.cmd [[
-- " skkeleten
-- " ==============================================================================
-- if !filereadable(expand('~/.config/skk/SKK-JISYO.L'))
--   call mkdir(expand('~/.config/skk'), 'p')
--   call system('cd ~/.config/skk && wget http://openlab.jp/skk/dic/SKK-JISYO.L.gz && gzip -d SKK-JISYO.L.gz')
-- endif
-- imap <C-j> <Plug>(skkeleton-toggle)
-- cmap <C-j> <Plug>(skkeleton-toggle)
-- call skkeleton#config({
--       \ "globalJisyo": expand("~/.config/skk/SKK-JISYO.L"),
--       \ "eggLikeNewline": v:true,
--       \})
-- 
-- call skkeleton#register_kanatable('rom', {
--       \   ',': ['，', ''],
--       \   '.': ['．', ''],
--       \ })
-- ]]
-- 
-- require'skkeleton_indicator'.setup{}
